[package]
name = "playground"
version = "0.1.0"
authors = ["paulg"]
edition = "2018"

[dependencies]
#enum-primitive-derive = "0.1"
#num-traits = "0.2"
#num-traits = "0.2"
#num-derive = "0.2"
bytes = "0.4"
failure = "0.1"

serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
num = "0.2"